### ISSUE TITLE
Add option to stream audio over HTTP

### ISSUE THREAD

**Issue by ZaneHannanAU** [open-dynaMIX/simple-mpv-webui#216]
Would be rather a chore, and having audio stream correctly even more so.... but, was interested in getting it to happen, so I could use audio with a handheld device (ie: phone) while viewing on an external device (ie: tv)

This is more of a wish than an issue, and would (probably) be at least some degree of a pain to implement (especially since the latency would be more variable than on-device).

Thank you.

**Comment by ZaneHannanAU** [comment]
nvm more or less solved through https://github.com/badaix/snapcast

**Comment by open-dynaMIX** [comment]
I had this idea for some time and have an implementation floating around in my git stash. My idea was to just stream the playing media file. To really make this work, a lot of changes would be necessary. Right now, requests to the webui are blocking, i.e. only one request at a time can be processed. There are many more things that would have to be done in order to make this work nice.

So I've decided to not implement it at all. If you want a streaming solution, use a tool that's build for that. IMO [snapcast](https://github.com/badaix/snapcast) is an excellent choice for that.
