### ISSUE TITLE
Cannot find main.* for any supported scripting backend in: ~/.config/mpv/scripts/webui-page

### ISSUE THREAD

**Issue by maksymsan** [open-dynaMIX/simple-mpv-webui#267]
I installed webui 2.1.0 in ~/.config/mpv/scripts, and mpv always prints this error message during start:
Cannot find main.* for any supported scripting backend in: ~/.config/mpv/scripts/webui-page

[mpv.log](https://github.com/open-dynaMIX/simple-mpv-webui/files/6291456/mpv.log)

Webui seems to be working well. 
Is anything wrong with my configuration?

**Comment by open-dynaMIX** [comment]
Thanks a lot for reporting this @maksymsan!

[mpv recently added support for loading scripts from directories](https://github.com/mpv-player/mpv/releases/tag/v0.33.0), which is awesome. In order for this to work, the main script file in a script directory must be called `main.*`.  If you added the webui with the `webui-page` dir into your scripts directory, mpv complains, it doesn't find a user script inside `webui-page`. That's normal, because this directory does not contain any userscript, but the static files served by the webui. As mpv is still correctly loading the webui userscript, there's nothing broken with your setup, except for having this message.

I've tried to adapt to the new way of including userscripts from directories (i.e. renaming `webui.lua` into `main.lua`), but unfortunately it is not 100% backward compatible for users using mpv < 0.33. That's why I've decided to wait a bit in order to keep the impact smaller.

If you want to get rid of the message, you can move the webui outside of the mpv `scripts` directory and include it with the `--script` option.

**Comment by francwalter** [comment]
OK, I installed it on Wincows 10 (64-Bit) with the pre-compiled Lua dll etc from the other repo and it works initially without any problems. The same warning is present, from this very issue, but I just ignore it 😄 
My issue with Mac OS 10.11.6 and Lua 5.4 from above is likely about the wrong Lua (5.4 instead of 5.1), my guess.
But not so important, I wont use it on Mac anyway, I need it on Windows, which is my media PC.
I was already astonished that the Lua 5.4 was installed by brew at all on Mac, as the brew is often not installing and compiling packages on this old OS (brew on 10.11 is not anymore supported, no way to fix that).

Anyway, maybe I could even fix it (with downgrading to Lua 5.1 with brew or installing it too, if possible) but as I dont need it here at the moment, I pass.

Nice work, by the way, thanks a lot for this GUI 🤣

**Comment by francwalter** [comment]
> I've tried to adapt to the new way of including userscripts from directories (i.e. renaming `webui.lua` into `main.lua`), but unfortunately it is not 100% backward compatible for users using mpv < 0.33. That's why I've decided to wait a bit in order to keep the impact smaller.
> 
> If you want to get rid of the message, you can move the webui outside of the mpv `scripts` directory and include it with the `--script` option.

I just created an empty file called main.lua into the webui-page directory and now the warning is away :)
So this is on Windows, but I guess the same for *nix systems.

**Comment by open-dynaMIX** [comment]
Hey @francwalter 

Nice, that you were able to solve your issue.

> I just created an empty file called main.lua into the webui-page directory and now the warning is away :)

This might be a workaround, but the proper fix is in #326 waiting to be finished and merged. Some more explanation is in the first comment of this issue.

**Comment by francwalter** [comment]
This was the first thing I tried, renaming webui.lua to main.lua, but it didn't solve the warning message.

**Comment by open-dynaMIX** [comment]
I think there was something else wrong, because I'm using that branch since quite some time.
