### ISSUE TITLE
error at startup: cannot find main.* for scripting backend

### ISSUE THREAD

**Issue by emk2203** [open-dynaMIX/simple-mpv-webui#351]
When I start mpv with the script installed, I get the following error:

```
$ DISPLAY=:0 mpv --playlist-start=10 --start=0:00 /nfs/n40lnas/\[SubsPlease\]\ Shiroi\ Suna\ no\ Aquatope\ -\ *
   cplayer: Cannot find main.* for any supported scripting backend in: /etc/mpv/scripts/webui-page
     webui: v2.2.0
     webui: [::]:8080
     webui: 192.168.88.51:8080 
   cplayer: Playing: /nfs/n40lnas/[SubsPlease] Shiroi Suna no Aquatope - 11 (720p) [18AD4A03].mkv
   cplayer:  (+) Video --vid=1 (*) (h264 1280x720 23.976fps)
   cplayer:  (+) Audio --aid=1 --alang=jpn (*) (aac 2ch 44100Hz)
   cplayer:  (+) Subs  --sid=1 --slang=eng (*) 'English subs' (ass)
        vd: Using hardware decoding (nvdec-copy).
   cplayer: AO: [alsa] 44100Hz stereo 2ch s32
   cplayer: VO: [gpu] 1280x720 nv12
statusline: (Paused) AV: 00:00:14 / 00:23:37 (1%) A-V:  0.000 DS: 3.000/0 Cache: 285s/150MB
   cplayer: 
   cplayer: Playing: /nfs/n40lnas/[SubsPlease] Shiroi Suna no Aquatope - 12 (720p) [3CEABAAE].mkv
     webui: Could not fetch "remaining" from mpv. 
     webui: Could not fetch "chapters" from mpv. 
     webui: Could not fetch "position" from mpv. 
     webui: Could not fetch "metadata" from mpv. 
     webui: Could not fetch "duration" from mpv. 
     webui: This is normal during startup. 
```
The script works otherwise. Is there some functionality lacking if `main.*` cannot be found? Also, the options are not working for me in `mpv.conf`. I am using `script-opts=webui-static_dir='/etc/mpv/webui-page'` or `'/etc/mpv/webui-page/static'` and the directory cannot be found.

**Comment by open-dynaMIX** [comment]
I think there are tw separate things going on here:

## Warning about missing `main.*`

The warning `Cannot find main.* for any supported scripting backend in: /etc/mpv/scripts/webui-page` is shown when using mpv >=v0.33.0 and the webui up until v2.2.0. This is because of the new way of including scripts in directories. This has been tracked in #267 and resolved in #326. This is already in master and will soon be included in v3.0.0.
This is just a warning, the webui will work despite of it.
Beware, if you switch to current master or to the soon to be released v3.0.0, read the README for instructions about installation/configuration.

## Usage of the [`static_dir`](https://github.com/open-dynaMIX/simple-mpv-webui#static_dir)-option

This option is meant to be used if you want to have the webui webserver to serve a custom frontend or moved the included frontend directory (`webui-page`) to a different location. As of now you're not warned, if this directory does not exists (this could be improved), but it will respond with a 404 when trying to access the frontend (`index.html` for example).
Do you really have frontend files in `/etc/mpv/webui-page` or `/etc/mpv/webui-page/static` or was this just an attempt to get rid of the warning above?

**Comment by emk2203** [comment]
Thanks for the quick answer to clarify things. Looking forward to v3.0.0 then.

Regarding the `static_dir` option, I was trying to keep a clean scripts directory and get the `webui-page` folder out of the scripts dir, so I tried to move it into the parent `/etc/mpv` directory. My ideal setup would be a renamed `main.lua` to `webui.lua` and `webui-page` moved out of the scripts directory. The rename was successful, the move of the directory not.

Regarding the need for it: I know from experience that when something acts up half a year from now and I look at the config, I won't know what is what with a cluttered system and a nondescript lua script name when troubleshooting. There are already six to eight scripts in there.

**Comment by open-dynaMIX** [comment]
I think you misunderstand the [new mpv way of including scripts in directories](https://mpv.io/manual/stable/#script-location). With the current webui-`main` branch or the upcoming release, you're able to just clone the whole project-directory inside your scripts directory and mpv automatically detects a `main.*`-file as the main script of this directory. This makes it easy to update (or just `git pull` new changes). You will not have a `main.lua`-file inside your scripts dir, but a `simple-mpv-webui`-directory containing the `main.lua`. This is also explained in the [updated usage section](https://github.com/open-dynaMIX/simple-mpv-webui#usage) of the README.
Because your mpv version is recent enough for this, mpv tries to find a `main.*`-file inside the `webui-page` directory (because this dir exists in your scripts-dir), but doesn't find one and warns you about that.
If you want to wait for the new release, I guess you can add an empty `main.lua` file inside `webui-page` to get rid of this warning. But it's really just preventing this warning, everything works as expected already.

**Comment by emk2203** [comment]
Thanks, this makes it clearer for me. This concept certainly has a lot of upsides by automating config upgrades. Traditionally, I am more used to `/etc` having only the absolutely needed configs and dirs, no `README`s, `.gitignore`s and such, that's why I pulled script and dir out of the github clone and ran into the issue. 

Having the empty `main.lua` might be a good compromise for now.

**Comment by open-dynaMIX** [comment]
[v3.0.0 is released](https://github.com/open-dynaMIX/simple-mpv-webui/releases/tag/v3.0.0).

Just in case you don't know: It's not necessary to put the scripts under `/etc`. You can also put them in the config dir in your home (ususally `~/.config/mpv/scripts/`). That way you don't clutter `/etc` and don't need to be root to manipulate/update them. Of course, then they just can be used by this particular user.
