### ISSUE TITLE
remove unwanted text when opening

### ISSUE THREAD

**Issue by omaru-ok** [open-dynaMIX/simple-mpv-webui#422]
i am getting this error
```
Cannot find main.* for any supported scripting backend in: C:/Users/O_0/scoop/apps/mpv-git/current/portable_config/scripts/webui-page
```
also this i want to remove this from pop-up  when i enter mpv
![image](https://user-images.githubusercontent.com/108952834/198894795-b86de870-f516-491a-a25e-91b6c679de32.png)

**Comment by open-dynaMIX** [comment]
> ```
> Cannot find main.* for any supported scripting backend in: C:/Users/O_0/scoop/apps/mpv-git/current/portable_config/scripts/webui-page
> ```

This is a warning shown on MPV version >=0.33.0 when the old installation method for the webui is used. I assume in your scripts directory you have `main.lua` and the `webui-page`. This warning will go away, if you put them into a sub-directory. Or you just delete them and do:

```bash
cd ~/.config/mpv/scripts/  # might be different in your setup
git clone git@github.com:open-dynaMIX/simple-mpv-webui.git
```

That way you can always just `git pull` any new changes.

> also this i want to remove this from pop-up when i enter mpv
> ![image](https://user-images.githubusercontent.com/108952834/198894795-b86de870-f516-491a-a25e-91b6c679de32.png)

This can be achieved from MPV itself with `--msg-level=simple_mpv_webui=no` (with your current setup it's  `--msg-level=main=no`). I suggest setting it to `warn` or `error` instead of `no`. The documentation for this flag can be found [here](https://mpv.io/manual/stable/#options-msg-level).

**Comment by omaru-ok** [comment]
>`This warning will go away, if you put them into a sub-directory. Or you just delete them and do`
this worked like a charm 😄



> `--msg-level=main=no`
this worked but only at the terminal output , 
![image](https://user-images.githubusercontent.com/108952834/199220766-930bf6fc-7cb9-44c6-865b-f6260a0fe0b5.png)


but not at mpv OSD it self 

![image](https://user-images.githubusercontent.com/108952834/199220740-f02588a8-8688-49fc-991e-4bd6eb828379.png)

a example video 
Uploading 2022-11-01_16-47-24.mp4…

**Comment by open-dynaMIX** [comment]
You can disable osd-logging with `--script-opts-add=webui-osd_logging=no`.

**Comment by open-dynaMIX** [comment]
I assume this is resolved. Feel free to reopen @omaru-ok if you still have an issue.
